import type { DbListing, DbUser, DbAgent } from '@/db/schema';
import type { Property, Agent, ListingCover, RegionProfile, NearbyPOI } from './types';

export function rowToProperty(r: DbListing): Property {
  const cover: ListingCover = {
    kind: r.coverKind,
    src: r.coverSrc ?? (r.images[0] ?? ''),
  };
  return {
    id: r.id,
    slug: r.slug,
    title: r.title,
    description: r.description,
    type: r.type,
    purpose: r.purpose,
    tier: r.tier,
    country: r.country,
    city: r.city,
    district: r.district,
    neighborhood: r.neighborhood ?? undefined,
    address: r.address ?? '',
    coords: { lat: r.lat ?? 0, lng: r.lng ?? 0 },
    price: r.price,
    currency: r.currency,
    area: { net: r.netArea, gross: r.grossArea },
    rooms: r.rooms,
    bathrooms: r.bathrooms,
    floor: r.floor,
    totalFloors: r.totalFloors,
    buildingAge: r.buildingAge,
    heating: r.heating,
    parking: r.parking,
    balcony: r.balcony,
    furnished: r.furnished,
    elevator: r.elevator,
    pool: r.pool,
    gym: r.gym,
    sauna: r.sauna,
    inSite: r.inSite,
    status: r.status,
    ownerType: r.ownerType,
    titleDeed: r.titleDeed,
    swappable: r.swappable,
    images: r.images,
    video: r.video ?? undefined,
    has360: r.has360,
    aiVerified: r.aiVerified,
    istbakuApproved: r.istbakuApproved,
    approvalLevel: r.approvalLevel as 0 | 1 | 2 | 3,
    publishedAt: r.publishedAt.toISOString(),
    views: r.views,
    favorites: r.favoritesCount,
    agentId: r.agentId ?? '',
    score: {
      total: r.scoreTotal,
      region: r.scoreRegion,
      price: r.scorePrice,
      rentYield: r.scoreRentYield,
      demand: r.scoreDemand,
      reasoning: r.scoreReasoning,
    },
    isPrivate: r.isPrivate,
    tags: r.tags,
    cover,
    regionProfile: r.regionProfile as RegionProfile,
    nearby: r.nearby as NearbyPOI,
    dailyRentalEnabled: r.dailyRentalEnabled,
    dailyRentalPricePerNight: r.dailyRentalPricePerNight ?? undefined,
    dailyRentalCurrency: r.dailyRentalCurrency ?? undefined,
    dailyRentalMinNights: r.dailyRentalMinNights,
    dailyRentalNotes: r.dailyRentalNotes ?? undefined,
  };
}

export function rowsToAgent(u: DbUser, a: DbAgent): Agent {
  return {
    id: u.id,
    name: u.name,
    agency: a.agency ?? undefined,
    avatar: u.avatar ?? '',
    phone: `${u.phoneDial ?? ''} ${u.phone ?? ''}`.trim(),
    whatsapp: a.whatsappNumber ?? `${u.phoneDial ?? ''} ${u.phone ?? ''}`.trim(),
    rating: a.rating,
    reviewsCount: a.reviewsCount,
    responseMins: a.responseMins,
    verified: a.verified,
    performance: a.performance,
    listingsCount: a.listingsCount,
    language: (a.languages ?? []) as Agent['language'],
    memberSince: a.memberSince.toISOString(),
    bio: u.bio ?? undefined,
  };
}
